### ISSUE TITLE
Version 0.8.1 Causes VASP Tests fail

### ISSUE THREAD

**Issue by xhqu1981** [materialsvirtuallab/monty#25]
When reporting bugs/issues, please supply the following information. If this 
is a feature request, please simply state the requested feature.

## System

* Monty version: 0.8.1
* Python version: 3.5.1
* OS version: Mac OS X

## Summary

Version 0.8.1 cause pymatgen VASP tests fail. Revert to version 0.8.0 works.

## Example code

pymatgen/io/vasp/tests/test_outputs.py

## Error message

Error
Traceback (most recent call last):
  File "/Users/xiaohuiqu/PycharmProjects/pymatgen/pymatgen/io/vasp/tests/test_outputs.py", line 479, in test_get_band_structure
    'KPOINTS_Si_bands'))
  File "/Users/xiaohuiqu/PycharmProjects/pymatgen/pymatgen/io/vasp/outputs.py", line 670, in get_band_structure
    dict_eigen = self.as_dict()['output']['eigenvalues']
  File "/Users/xiaohuiqu/PycharmProjects/pymatgen/pymatgen/io/vasp/outputs.py", line 1136, in as_dict
    d["reduced_cell_formula"] = Composition(comp.reduced_formula).as_dict()
  File "/Users/xiaohuiqu/PycharmProjects/pymatgen/pymatgen/core/composition.py", line 384, in reduced_formula
    return self.get_reduced_formula_and_factor()[0]
  File "/Users/xiaohuiqu/PycharmProjects/pymatgen/pymatgen/core/composition.py", line 349, in get_reduced_formula_and_factor
    (formula, factor) = reduce_formula(d)
  File "/Users/xiaohuiqu/PycharmProjects/pymatgen/pymatgen/core/composition.py", line 775, in reduce_formula
    factor = abs(gcd(*sym_amt.values()))
  File "/Users/xiaohuiqu/program/python_virtual_envs/3.x/3.5/xq_py3/lib/python3.5/site-packages/monty/fractions.py", line 33, in gcd
    n = pygcd(n, i)
TypeError: 'float' object cannot be interpreted as an integer

<Error message>

## Suggested solution (if known)

convert all the parameters to float before calling pygcd()

## Files

pymatgen/io/vasp/tests/test_outputs.py
```
<contents of file 1>
```

**Comment by shyuep** [comment]
No, this is actually a problem of pymatgen loose usage of the gcd function. gcd is defined only for integers. I have corrected the problem in pymatgen.
