### ISSUE TITLE
import monty.json catch ModuleNotFoundError

### ISSUE THREAD

**Issue by njzjz** [materialsvirtuallab/monty#57]
When reporting bugs/issues, please supply the following information. If this 
is a feature request, please simply state the requested feature.

## System

* Monty version: 3.0.1
* Python version: 3.7
* OS version: Linux

## Summary

* cannot import monty.json

## Example code

```python
import monty.json
```

## Error message

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/monty/json.py", line 29, in <module>
    import ruamel.yaml as yaml
ModuleNotFoundError: No module named 'ruamel'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/monty/json.py", line 31, in <module>
    import yaml  # type: ignore
ModuleNotFoundError: No module named 'yaml'
```
https://travis-ci.com/njzjz/gist/builds/130067815

## Suggested solution (if known)

* 2.0.6 is OK. Something broken?

**Comment by shyuep** [comment]
Yes, this was a bug introduced in the v3. I just released v3.0.2 that fixes this. Thanks.
